### ISSUE TITLE
Update Url打开之后是404

### ISSUE THREAD

**Issue by godlikeanyone** [nlnlnull/xTeko#1]

**Comment by uclort** [comment]
昨天不小心删除了，重新安装一下。
[安装链接](https://xteko.com/redir?name=%E6%96%97%E5%9B%BE&url=https://github.com/nlnlnull/xTeko/blob/master/doutu/.output/doutu.box?raw=true&icon=icon_055.png)

**Comment by godlikeanyone** [comment]
谢谢大佬，这修复速度给力
